### ДЗ 4. Урок 6&7. Системы линейных уравнений#

### -- Автор: Шенк Евгений Станиславович

### !!! Данный файл является дополнением к файлу ДЗ_ 4 _Шенк_ЕС.docx

In [1]:
import math
import numpy as np
import scipy.linalg as lin

### Задание 6.2.

In [2]:
# а
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -7, 0])
x = lin.solve(a,b)
print (f'x:\n {x}\n')

x:
 [1.   0.75 1.75]



### Задание 6.3.

In [3]:
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
x = lin.solve(a,b)
print (f'x:\n {x}\n')

x:
 [2.76666667 0.3        1.33333333 0.5       ]



### Задание 7.1.

In [4]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
lin.det(a)

43.0

In [5]:
a1=np.column_stack([b,a[:,1:]])
detA1=np.linalg.det(a1)
print (f'a1:\n {a1}\n\n{detA1}')

a1:
 [[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

86.00000000000004


In [6]:
a2=np.column_stack([a[:,0],b,a[:,2:]])
detA2=np.linalg.det(a2)
print (f'a1:\n {a2}\n\n{detA2}')

a1:
 [[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

-43.000000000000014


In [7]:
a3=np.column_stack([a[:,:2],b])
detA3=np.linalg.det(a3)
print (f'a1:\n {a3}\n\n{detA3}')

a1:
 [[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

42.99999999999998


In [8]:
x = lin.solve(a,b)
print (f'x:\n {x}\n')

x:
 [ 2. -1.  1.]



### Задание 7.2.

In [9]:
a = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
lin.lu_factor(a)

(array([[ 3.        , 26.        , 30.        ],
        [ 0.66666667, -8.33333333, -8.        ],
        [ 0.33333333,  0.8       ,  0.4       ]]),
 array([2, 1, 2], dtype=int32))

In [10]:
u = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
l = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
l.dot(u)

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

In [11]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
lin.lu_factor(a)

(array([[  4.        ,  22.        ,  53.        ,  33.        ],
        [  0.5       ,  -6.        , -18.5       ,  -7.5       ],
        [  0.75      ,  -0.25      , -15.375     ,  -8.625     ],
        [  0.25      ,   0.75      ,  -0.17073171,  -0.09756098]]),
 array([3, 1, 2, 3], dtype=int32))

In [12]:
u = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3 ,1], [0, 0, 0, 4]])
l = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
l.dot(u)

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

### Задание 7.3.

In [13]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
lu, piv = lin.lu_factor(a)
lin.lu_solve((lu, piv), b)

array([-1.00000000e+00,  2.44249065e-16,  1.00000000e+00])

In [14]:
lin.solve(a, b)

array([-1.00000000e+00,  2.44249065e-16,  1.00000000e+00])

### Задание 7.4.

In [15]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])
lin.solve(a, b)

array([ 6., -5., -4.])