### ДЗ 2. Урок 3&4. Матрицы и матричные операции#

### -- Автор: Шенк Евгений Станиславович

### !!! Данный файл является дополнением к файлу ДЗ_ 2 _Шенк_ЕС.docx

In [1]:
import math
import numpy as np
import numpy.linalg as lin

### Задание 3.1.

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

In [2]:
#1.а
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
A.shape, B.shape

((4, 2), (4, 2))

In [3]:
# np.dot(A, B)

In [4]:
# np.dot(B, A)

In [5]:
#1.б
A = np.array([[1, 2, 3, 4 ,5], [6, 7, 8, 9, 10]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12],  [13, 14, 15]])
A.shape, B.shape

((2, 5), (5, 3))

In [6]:
np.dot(A, B).shape

(2, 3)

In [7]:
# np.dot(B, A)

In [8]:
#1.в
A = np.arange(24).reshape(8,3)
B = np.arange(24).reshape(3,8)
A.shape, B.shape

((8, 3), (3, 8))

In [9]:
np.dot(A, B).shape, np.dot(B, A).shape

((8, 8), (3, 3))

In [10]:
#1.г
A = np.arange(16).reshape(4,4)
B = np.arange(16).reshape(4,4)
A.shape, B.shape

((4, 4), (4, 4))

In [11]:
np.dot(A, B).shape, np.dot(B, A).shape

((4, 4), (4, 4))

### Задание 3.2.

In [12]:
A = np.array([1, -2, 3, 0]).reshape(2, 2)
B = np.array([4, -1, 0, 5]).reshape(2, 2)

In [13]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [14]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

### Задание 3.3.

In [15]:
A = np.array([1, 7, 3, -6]).reshape(2, 2)
B = np.array([0, 5, 2, -1]).reshape(2, 2)
C = np.array([2, -4, 1, 1]).reshape(2, 2)
3*A - 2*B +4*C

array([[ 11,  -5],
       [  9, -12]])

### Задание 3.4.

In [16]:
A = np.array([4, 1, 5, -2, 2, 3]).reshape(3, 2)

In [17]:
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [18]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [19]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

### Задание 4.1.

In [20]:
A = np.array([np.sin(30), -np.cos(30), np.cos(30), np.sin(30)]).reshape(2, 2)

In [21]:
lin.det(A)

1.0

In [22]:
A = np.array([4, 2, 3, 0, 5, 1, 0, 0, 9]).reshape(3, 3)

In [23]:
lin.det(A)

180.0

In [24]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)

In [25]:
lin.det(A)

-9.51619735392994e-16

### Задание 4.2.

In [26]:
A = np.array([1, 2, 3, 0, 2, 6, 0, 0, 2]).reshape(3, 3)

In [27]:
lin.det(A)

4.0

In [28]:
lin.det(A.dot(A))

15.999999999999998

In [29]:
lin.det(A.T)

4.000000000000001

In [30]:
lin.det(2*A)

31.999999999999986

### Задание 4.3.

In [31]:
A = np.array([-2, 7, -3, 4, -14, 6, -3, 7, 13]).reshape(3, 3)

In [32]:
lin.det(A)

0.0

### Задание 4.4.

In [33]:
A = np.array([1, 2, 3, 1, 1, 1, 2, 3, 4]).reshape(3, 3)

In [34]:
lin.matrix_rank(A)

2

In [35]:
A = np.array([0, 0, 2, 1, 0, 0, 2, 2, 0, 0, 4, 3, 2, 3, 5, 6]).reshape(4, 4)

In [36]:
lin.matrix_rank(A)

3