### ДЗ 3. Урок 5. Линейные преобразования#

### -- Автор: Шенк Евгений Станиславович

### !!! Данный файл является дополнением к файлу ДЗ_ 3 _Шенк_ЕС.docx

In [1]:
import math
import numpy as np
import numpy.linalg as lin

### Задание 5.1.

1. Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей:

In [2]:
A = np.array([-1, -6, 2, 6]).reshape(2, 2)

In [3]:
w, v = lin.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


In [4]:
v[1][0] / v[0][0] #лямбда =2 Здесь х2/х1

-0.5

In [5]:
v[1][1] / v[0][1] #лямбда =3 Здесь х2/х1

-0.6666666666666669

Сотношение х1 и х2 совпадает с расчетом вручную

### Задание 5.2.

In [6]:
A = np.array([-1, 0, -1, 0]).reshape(2, 2)

In [7]:
w, v = lin.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[ 0. -1.]
Собственные векторы:
[[0.         0.70710678]
 [1.         0.70710678]]


### Задание 5.3.

In [8]:
A = np.array([1, 1, -1, 3]).reshape(2, 2)

In [9]:
w, v = lin.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2.00000002 1.99999998]
Собственные векторы:
[[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


### Задание 5.4.

In [10]:
A = np.array([0, 3, 0, 3, 0, 0, 0, 0, 3]).reshape(3, 3)

In [11]:
w, v = lin.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
